# .github/workflows/scrape.yml

name: Update Prices Daily

on:
  schedule:
    - cron: '0 3 * * *'  # Täglich um 3:00 UTC
  workflow_dispatch:      # Manuell auslösbar
  
permissions:
  contents: write  
  
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Scraper
      run: python .github/workflows/scraper.py


    - name: Commit & Push Results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add prices_*.json
        git commit -m "🔄 Auto-update prices"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}






