name: Update Prices Daily

on:
  schedule:
    - cron: '0 4 * * *'  # täglich um 4:00 UTC (6:00 deutscher Zeit)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Scraper
        run: python .github/workflows/scraper.py


      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add prices.json
          git diff --cached --quiet || git commit -m "Auto-update prices" && git push
