name: Update Prices Daily

on:
  schedule:
    - cron: '4 4 * * *'  # Täglich um 04:04 UTC (06:04 deutscher Zeit)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        run: python .github/workflows/scraper.py

      - name: Zeige Inhalte des Workspaces
        run: ls -la

      - name: Commit and Push JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add prices/prices_*.json
          git add history/
          git commit -m "📈 Add historical price logs for all sets"
          git push

          git commit -m "Auto-update prices" || echo "Nichts zu committen"
          git push
